import { DataTypes } from "sequelize";
import bcrypt from 'bcrypt';

import { dbSequelize } from "../db";
export const User = dbSequelize.define('User', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    username: {
        type: DataTypes.STRING,
        allowNull: false
    },
    email: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
            isEmail: true,
            len: [4, 254],
        }
    },
    password: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
            len: [12, 60] // 60 characters is the hash generated by bcrypt
        }
    },
    avatar: {
        type: DataTypes.STRING,
        allowNull: true,
        // defaultValue: 'default profile picture url'
        validate: {
            isUrl: true,
        }
    },
    name: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    description: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    location: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    dietaryPreferences:{
        type: DataTypes.STRING,
        allowNull: true,
    },
    createdAt: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW(),
        validate: {
            isDate: true,
        }
    },
    updatedAt: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW(),
        validate: {
            isDate: true,
        }
    },
    deletedAt: {
        type: DataTypes.DATE,
        allowNull: true,
        defaultValue: null,
        validate: {
            isDate: true,
        }
    },
    isDeleted: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        allowNull: true,
        validate: {
            isBoolean: true,
        }
    }
    // favorites: {
    // relation with recipes
    // },
    // createdRecipes: {
    // relation with recipes
    // }
});

User.beforeCreate(async (user: any) => {
    user.password = await bcrypt.hash(user.password, 10);
})