import { DataTypes } from "sequelize";
import { dbSequelize } from "../db";

export const User = dbSequelize.define('User', {
    username: {
        type: DataTypes.STRING,
        allowNull: false
    },
    email: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
            isEmail: true,
            len: [1, 254],
        }
    },
    password: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
            length: [60] // 60 characters is the hash generated by bcrypt
        }
    },
    name: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    avatar: {
        type: DataTypes.STRING,
        allowNull: true,
        // defaultValue: 'default profile picture url'
        validate: {
            isUrl: true,
        }
    },
    location: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    dietaryPreferences:{
        type: DataTypes.STRING,
        allowNull: true,
    },
    createdAt: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW(),
        validate: {
            isDate: true,
        }
    },
    updatedAt: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW(),
        validate: {
            isDate: true,
        }
    },
    deletedAt: {
        type: DataTypes.DATE,
        allowNull: true,
        defaultValue: null,
        validate: {
            isDate: true,
        }
    },
    isDeleted: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        allowNull: false,
        validate: {
            isBoolean: true,
        }
    }
    // favorites: {
    // relation with recipes
    // },
    // createdRecipes: {
    // relation with recipes
    // }
})